import type { AirdropCampaign } from './types'

// Static sample data. Replace with a fetch from the campaigns API when the
// backend claim/eligibility endpoints land.
export const SAMPLE_CAMPAIGNS: AirdropCampaign[] = [
  {
    id: 'altaris-genesis',
    name: 'Altaris Genesis Drop',
    symbol: 'ALTR',
    description: 'Exclusive genesis airdrop for early Altaris Capital platform users. Unlock premium features and governance rights.',
    logo: 'https://altaris-capital.vercel.app/icons/icon-192x192.png',
    banner: '',
    totalAllocation: '50,000,000 ALTR',
    tokenPrice: '$0.15',
    eligibility: 'open',
    status: 'active',
    startDate: '2026-05-01',
    endDate: '2026-06-30',
    claimed: false,
    claimAmount: '2,500 ALTR',
    claimProgress: 68,
    tags: ['Genesis', 'Governance'],
    requirements: ['Connect wallet', 'Complete profile', 'Hold minimum $100'],
    network: 'Ethereum',
    contractAddress: '0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb',
  },
  {
    id: 'eth-staker-rewards',
    name: 'ETH Staker Rewards',
    symbol: 'stETH',
    description: 'Rewarding Ethereum stakers with bonus Lido stETH tokens for supporting network decentralization.',
    logo: 'https://cryptologos.cc/logos/lido-staked-ether-steth-logo.png',
    banner: '',
    totalAllocation: '10,000 stETH',
    tokenPrice: '$3,842.50',
    eligibility: 'holders',
    status: 'active',
    startDate: '2026-05-10',
    endDate: '2026-07-15',
    claimed: false,
    claimAmount: '0.5 stETH',
    claimProgress: 42,
    tags: ['Staking', 'ETH'],
    requirements: ['Hold ETH or stETH', 'Stake minimum 0.1 ETH', '30-day holding period'],
    network: 'Ethereum',
    contractAddress: '0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84',
  },
  {
    id: 'solana-ecosystem',
    name: 'Solana Ecosystem Boost',
    symbol: 'SOLB',
    description: 'Community airdrop for Solana ecosystem participants. Boost your DeFi yields across the Solana network.',
    logo: 'https://cryptologos.cc/logos/solana-sol-logo.png',
    banner: '',
    totalAllocation: '5,000,000 SOLB',
    tokenPrice: '$0.08',
    eligibility: 'wallet',
    status: 'active',
    startDate: '2026-05-12',
    endDate: '2026-06-20',
    claimed: false,
    claimAmount: '10,000 SOLB',
    claimProgress: 55,
    tags: ['Solana', 'DeFi'],
    requirements: ['Solana wallet', 'Minimum 1 SOL balance', 'Active in last 30 days'],
    network: 'Solana',
    contractAddress: 'SOLB-token-address',
  },
  {
    id: 'defi-governance',
    name: 'DeFi Governance Token',
    symbol: 'DGOV',
    description: 'Governance token for the next generation of decentralized finance protocols. Vote on protocol upgrades and treasury allocations.',
    logo: 'https://cryptologos.cc/logos/uniswap-uni-logo.png',
    banner: '',
    totalAllocation: '100,000,000 DGOV',
    tokenPrice: '$0.25',
    eligibility: 'staked',
    status: 'upcoming',
    startDate: '2026-06-01',
    endDate: '2026-08-31',
    claimed: false,
    claimAmount: '5,000 DGOV',
    claimProgress: 0,
    tags: ['Governance', 'DeFi'],
    requirements: ['Stake LP tokens', 'Participate in governance', 'Hold qualifying assets'],
    network: 'Ethereum',
    contractAddress: '0xDGOV...token',
  },
  {
    id: 'btc-lightning',
    name: 'Lightning Network Rewards',
    symbol: 'LNR',
    description: 'Incentivizing Bitcoin Lightning Network adoption with instant, low-fee transactions.',
    logo: 'https://cryptologos.cc/logos/bitcoin-btc-logo.png',
    banner: '',
    totalAllocation: '1,000,000 LNR',
    tokenPrice: '$1.20',
    eligibility: 'wallet',
    status: 'upcoming',
    startDate: '2026-06-15',
    endDate: '2026-09-15',
    claimed: false,
    claimAmount: '500 LNR',
    claimProgress: 0,
    tags: ['Bitcoin', 'Lightning'],
    requirements: ['Lightning wallet', 'Minimum 5 transactions', 'Channel open for 14 days'],
    network: 'Bitcoin Lightning',
    contractAddress: 'ln-rewards-address',
  },
  {
    id: 'ai-crypto-rewards',
    name: 'AI x Crypto Rewards',
    symbol: 'AIC',
    description: 'Bridging AI and blockchain. Rewards for early adopters of AI-powered DeFi tools and agents.',
    logo: 'https://cryptologos.cc/logos/near-protocol-near-logo.png',
    banner: '',
    totalAllocation: '25,000,000 AIC',
    tokenPrice: '$0.45',
    eligibility: 'open',
    status: 'active',
    startDate: '2026-05-08',
    endDate: '2026-07-08',
    claimed: false,
    claimAmount: '1,200 AIC',
    claimProgress: 73,
    tags: ['AI', 'Innovation'],
    requirements: ['Connect any wallet', 'Complete AI survey', 'Follow on social'],
    network: 'NEAR',
    contractAddress: '0xAIC...token',
  },
]
