export const INVESTMENT_PLANS = [
  {
    id: 'smart-save',
    name: 'Altaris Smart Save',
    description: 'Our flagship long-term wealth accumulation plan. Earns 40% annually with automatic reinvestment. Your balance grows every year — set it and let it work.',
    minDeposit: 500,
    dailyRoi: 0.00109589, // 40% / 365
    annualRoi: 40,
    duration: 365,
    risk: 'Low',
    riskColor: 'success',
    badge: 'Most Popular',
    badgeColor: 'success',
    category: 'long-term',
    activeInvestors: 8241,
    icon: 'piggy',
    hot: false,
  },
  {
    id: 'crypto-growth',
    name: 'Crypto Growth Fund',
    description: 'Diversified exposure to top 10 cryptocurrencies with active rebalancing and risk management.',
    minDeposit: 250,
    dailyRoi: 0.012,
    annualRoi: 438,
    duration: 30,
    risk: 'Medium',
    riskColor: 'warning',
    badge: null,
    badgeColor: null,
    category: 'medium',
    activeInvestors: 3412,
    icon: 'chart',
    hot: false,
  },
  {
    id: 'btc-yield',
    name: 'BTC Yield Vault',
    description: 'Bitcoin-focused high-yield strategy leveraging DeFi protocols and arbitrage opportunities.',
    minDeposit: 1000,
    dailyRoi: 0.025,
    annualRoi: 912,
    duration: 14,
    risk: 'High',
    riskColor: 'danger',
    badge: 'Hot',
    badgeColor: 'danger',
    category: 'high',
    activeInvestors: 1892,
    icon: 'bitcoin',
    hot: true,
  },
  {
    id: 'eth-liquidity',
    name: 'ETH Liquidity Pool',
    description: 'Provide liquidity to Ethereum-based protocols and earn from trading fees and yield farming.',
    minDeposit: 750,
    dailyRoi: 0.018,
    annualRoi: 657,
    duration: 21,
    risk: 'Medium-High',
    riskColor: 'warning',
    badge: null,
    badgeColor: null,
    category: 'medium',
    activeInvestors: 2156,
    icon: 'eth',
    hot: false,
  },
  {
    id: 'stablecoin-reserve',
    name: 'Stablecoin Reserve',
    description: 'Ultra-safe stablecoin lending strategy. Preserve capital while earning consistent daily returns.',
    minDeposit: 100,
    dailyRoi: 0.006,
    annualRoi: 219,
    duration: 60,
    risk: 'Low',
    riskColor: 'success',
    badge: 'Beginner Friendly',
    badgeColor: 'success',
    category: 'low',
    activeInvestors: 12847,
    icon: 'shield',
    hot: false,
  },
  {
    id: 'defi-accelerator',
    name: 'DeFi Accelerator',
    description: 'High-frequency DeFi strategy exploiting cross-chain arbitrage and flash loan opportunities.',
    minDeposit: 2000,
    dailyRoi: 0.035,
    annualRoi: 1277,
    duration: 7,
    risk: 'Very High',
    riskColor: 'danger',
    badge: 'Hot',
    badgeColor: 'danger',
    category: 'high',
    activeInvestors: 891,
    icon: 'zap',
    hot: true,
  },
  {
    id: 'global-index',
    name: 'Global Index Fund',
    description: 'Track the performance of the top 20 global crypto assets with quarterly rebalancing.',
    minDeposit: 500,
    dailyRoi: 0.011,
    annualRoi: 401,
    duration: 90,
    risk: 'Low-Medium',
    riskColor: 'success',
    badge: 'Stable',
    badgeColor: 'success',
    category: 'low',
    activeInvestors: 5634,
    icon: 'globe',
    hot: false,
  },
  {
    id: 'quantum-arbitrage',
    name: 'Quantum Arbitrage',
    description: 'AI-driven cross-exchange arbitrage executing thousands of trades per second for maximum gains.',
    minDeposit: 5000,
    dailyRoi: 0.042,
    annualRoi: 1533,
    duration: 7,
    risk: 'Very High',
    riskColor: 'danger',
    badge: 'Hot',
    badgeColor: 'danger',
    category: 'high',
    activeInvestors: 347,
    icon: 'cpu',
    hot: true,
  },
  {
    id: 'altaris-platinum',
    name: 'Altaris Platinum',
    description: 'Exclusive institutional-grade strategy for high-net-worth clients. Personal portfolio manager assigned.',
    minDeposit: 10000,
    dailyRoi: 0.05,
    annualRoi: 1825,
    duration: 30,
    risk: 'High',
    riskColor: 'warning',
    badge: 'VIP',
    badgeColor: 'warning',
    category: 'vip',
    activeInvestors: 128,
    icon: 'crown',
    hot: false,
  },
  {
    id: 'fixed-income',
    name: 'Fixed Income Bond',
    description: 'Structured bond product backed by real-world assets. Predictable returns with capital protection.',
    minDeposit: 300,
    dailyRoi: 0.008,
    annualRoi: 292,
    duration: 120,
    risk: 'Low',
    riskColor: 'success',
    badge: 'Capital Safe',
    badgeColor: 'success',
    category: 'low',
    activeInvestors: 7123,
    icon: 'landmark',
    hot: false,
  },
]

export function getPlanById(id: string) {
  return INVESTMENT_PLANS.find((p) => p.id === id)
}
